apiVersion: v1
kind: Namespace
metadata:
  name: k8s-playground
  labels:
    app.kubernetes.io/name: k8s-playground
    # Built-in Pod Security Admission. No Kyverno needed.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
